<a href="https://colab.research.google.com/github/pipuf/ml_dev_cert/blob/main/Copy_of_7_1_2_THEORY_Scikit_learn_Encoders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Encoders with Scikit-Learn

In [ ]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

data = ['small', 'medium', 'big', 'giant', 'big', 'giant', 'medium', 'small', 'small']
values = array(data)
print(values)

['small' 'medium' 'big' 'giant' 'big' 'giant' 'medium' 'small' 'small']


## Label Encoder

We transform the tags into integer numbers, between $0$ and $N_{classes}-1$

In [ ]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

[3 2 0 1 0 1 2 3 3]


## OneHot Encoder

We transform the integer numbers into one-hot binary arrays

In [ ]:
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [ ]:
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['small']
